import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
  TERM="xterm-256color"

[window]
padding = {x = 6, y = 6 }
title = "Alacritty"
opacity = 1.0

[font]
# brew tap homebrew/cask-fonts
# brew install font-jetbrains-mono-nerd-font
#normal = {family = "FiraCode Nerd Font", style = "Retina"}
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 14.0
offset = {x = 0, y= 0}
glyph_offset = {x = 0, y= 0}

## install alacritty-themes
## npm i -g alacritty-themes
## it will update the import at the top with a new theme
